teams = {
    "DamCon": {"icon": 176,
               "colour": "#3366ff",
               "tag": "DamCon",
               "move_speed": 0.03,
               "strength": 8,
               "orders": ["Auto-Repair", "Manual Repair"]},
    "Medics": {"icon": 180,
               "colour": "#009900",
                "tag": "Medical",
               "move_speed": 0.03,
               "strength": 2,
               "orders": ["Heal"]},
    "Marines": {"icon": 166,
                "colour": "#cc9900",
                "tag": "Security",
                "move_speed": 0.04,
                "strength": 5,
                "orders": ["Attack"]},
    "Combat Engineers": {"icon": 188,
                "colour": "#cc9900",
                "tag": "Security",
                "move_speed": 0.03,
                "strength": 3,
                "orders": ["Engineering"]},
    "Evacuees": {"icon": 194,
                 "colour": "#5DE2E7",
                 "tag": "Evacuee",
                 "move_speed": 0.03,
                 "strength": 1,
                 "orders": ["Critical"]}
}
